### ISSUE TITLE
Corrupt image after running mangle.sh with image

### ISSUE THREAD

**Issue by VirenMohindra** [robertfoss/audio_shop#10]
```
rm: illegal option -- -
usage: rm [-f | -i] [-dPRrvW] file ...
       unlink file
```

**Comment by robertfoss** [comment]
If you can provide me with a complete command and the input image you used, I'll try to replicate the behavior.

**Comment by VirenMohindra** [comment]
This error occurs with every flag (bass, echo, vol) etc.

I did install `sox` with HomeBrew but I don't think that should be a problem. I think the `cleanup()` function might play a role in this error.

I've run every command and it does produce an output image, but it is corrupted.

example:

![test](https://cloud.githubusercontent.com/assets/10460518/25450440/f360fae8-2a8c-11e7-9be9-508f279c3c2a.jpg)
![output](https://cloud.githubusercontent.com/assets/10460518/25450441/f36136ac-2a8c-11e7-8f09-7608c245c26c.jpg)



EDIT: The image doesn't preview well on Mac OSX but it appears the effect is applied even though the script still throws the error.

**Comment by robertfoss** [comment]
So which exact command did you issue?
And do you see any console errors?

**Comment by VirenMohindra** [comment]
Th error applies to every flag

I  used `./mangle.sh test.jpg output.jpg bass 2` for the above image.

verbose output in the console:

```
TMP_DIR:         /tmp/audio_shop-ewZnM
RES:             290x158
VIDEO:
AUDIO:
FFMPEG_IN_OPTS:
FFMPEG_OUT_OPTS:
SOX_OPTS:        bass 100
Extracting raw image data..
Processing as sound..
Recreating image data from audio..
rm: illegal option -- -
usage: rm [-f | -i] [-dPRrvW] file ...
       unlink file
```

**Comment by robertfoss** [comment]
Ok, I think I see what is happening here.
`rm -rf --preserve-root "${TMP_DIR}"` is being executed in an environment with a version of rm that doesnt support `--preserve-root`.

`--preserve-root` was a development safety measure and can be removed

**Comment by robertfoss** [comment]
Fixed here: https://github.com/robertfoss/audio_shop/commit/45d2871563bb2da2ba699b5b1afcdfd9993a9ed3
