### ISSUE TITLE
Cannot handle filenames containing spaces

### ISSUE THREAD

**Issue by Hagmar** [robertfoss/audio_shop#5]
There are a bunch of escapes missing, causing it to crash when the input and/or output filenames contain spaces.

**Comment by Hagmar** [comment]
All these changes were reverted when merging [Gandalf-'s pull request](https://github.com/robertfoss/audio_shop/commit/ddc409241a5870e91246ce4cdcbc19779a9b1f8b), so the issue is back again...

**Comment by robertfoss** [comment]
@Hagmar: ack, will have a look.

**Comment by robertfoss** [comment]
Fixed!
