### ISSUE TITLE
Cool!

### ISSUE THREAD

**Issue by mathisonian** [robertfoss/audio_shop#7]
Hey @robertfoss thanks for posting this, its a great idea. I would like to try out a version using real guitar pedals, I wonder if you could point me in the right direction -- 

I think to do this I would to do things - one, output the image as an audio signal to an audio interface, and two, read it back in from the input. It seems like you've solved the difficult problems of the audio/image conversion here, but I don't really understand where this is happening in your code

**Comment by schnjaso** [comment]
From my previous experiments (which were far glitchier and perhaps less
easy to get something useful) the most barebones way of doing this involves
simple changing the the file extension of your image to .wav, throwing it
into your daw of choice, and changing the printed version of the file back
to jpg or whatever

**Comment by robertfoss** [comment]
@mathisonian I have played with the idea, but I'm not sure how to realize it.

I see 2 problems:
  - Figuring out where an image starts and ends.
  - The low bandwidth of audio equipment (only 44khz ie 44kbits/s)

**Comment by mathisonian** [comment]
@robertfoss good points. figuring out a system to handle the image start/end isn't obvious to me, but i'll think about it a little more. I'll update this issue if I make any progress
